title: Eriko Funasato # your name (or website title) here
logo: "/images//eriko_professional_1%20(2).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a Data Scientist Intern at Bold, San Mateo. MS in Data Science at University of San Francico. BA in Applied Mathematics at University of California, Berkeley.
  <br><br>
  <a href="https://www.linkedin.com/in/eriko-funasato-503/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
